#!/usr/bin/env python3
"""Validate an untrusted issue request; update only its enrolled virtual IP.

No request field is executed, interpolated into shell, or used as a file path.
The GitHub actor and creation time come from the server event, not the payload.
"""
import datetime as dt
import ipaddress
import json
from pathlib import Path
import re
import sys
import tomllib

TITLE = "[FaekNET registry] endpoint update"
NETWORK = ipaddress.ip_network("10.66.0.0/24")
MAX_BYTES = 131072
TTL = 7 * 86400
FIELDS = {"schema_version", "name", "virtual_ip", "public_ip", "public_port"}


def validate_endpoint(data):
    if set(data) != FIELDS or type(data["schema_version"]) is not int or data["schema_version"] != 1:
        raise ValueError("Invalid request fields or schema version")
    if not isinstance(data["name"], str) or not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_-]{0,31}", data["name"]):
        raise ValueError("Name must be 1-32 letters, digits, underscores or hyphens")
    if not isinstance(data["virtual_ip"], str) or not isinstance(data["public_ip"], str):
        raise ValueError("Addresses must be IPv4 strings")
    vip = ipaddress.IPv4Address(data["virtual_ip"])
    if vip not in NETWORK or vip in (NETWORK.network_address, NETWORK.broadcast_address):
        raise ValueError("Virtual IP must be a host in 10.66.0.0/24")
    ip = ipaddress.IPv4Address(data["public_ip"])
    if not ip.is_global or ip.is_multicast or ip.is_reserved:
        raise ValueError("Public endpoint must be a globally routable IPv4 address")
    if type(data["public_port"]) is not int or not 1 <= data["public_port"] <= 65535:
        raise ValueError("Port must be 1-65535")
    return dict(data)


def update(event, enrollment, directory, now):
    issue = event.get("issue", {})
    if event.get("action") != "opened" or "pull_request" in issue or issue.get("title") != TITLE:
        raise ValueError("Not a registry request")
    # Only the original author's fresh issue body is eligible. Later edits do
    # not trigger this workflow, and edited bodies are rejected defensively.
    if issue.get("created_at") != issue.get("updated_at"):
        raise ValueError("Edited requests are not accepted; submit a new request")
    body = issue.get("body") or ""
    if len(body.encode("utf-8")) > 2048:
        raise ValueError("Request too large")
    request = validate_endpoint(tomllib.loads(body))
    author = issue.get("user", {}).get("login", "").lower()
    if not author or issue.get("user", {}).get("type") != "User":
        raise ValueError("A GitHub user login is required")
    if enrollment.get("schema_version") != 1 or directory.get("schema_version") != 1:
        raise ValueError("Invalid registry schema")
    owners = {}
    for login, addresses in enrollment.get("members", {}).items():
        if not isinstance(addresses, list):
            raise ValueError("Enrollment addresses must be arrays")
        for address in addresses:
            if address in owners:
                raise ValueError("Virtual IP assigned more than once")
            owners[address] = login.lower()
    if owners.get(request["virtual_ip"]) != author:
        raise ValueError("GitHub user is not enrolled for this virtual IP")
    created = int(dt.datetime.fromisoformat(issue["created_at"].replace("Z", "+00:00")).timestamp())
    if created > now + 60 or now - created > 86400:
        raise ValueError("Request is stale or future-dated")
    peers = directory.get("peers", [])
    if len(peers) > 254:
        raise ValueError("Directory too large")
    result = []
    for peer in peers:
        if peer["virtual_ip"] == request["virtual_ip"]:
            if peer["updated_at"] >= created:
                return directory  # Out-of-order workflow/replay: no rollback.
        elif peer["expires_at"] > now and owners.get(peer["virtual_ip"]) == peer["owner"].lower():
            result.append(peer)
    request.pop("schema_version")
    result.append(dict(request, owner=author, updated_at=created, expires_at=created + TTL))
    return {"schema_version": 1, "peers": sorted(result, key=lambda p: int(ipaddress.IPv4Address(p["virtual_ip"])))}


def encode(directory):
    lines = ["# Public endpoints only. Generated by the peer-registry workflow.", "schema_version = 1"]
    if not directory["peers"]:
        lines.append("peers = []")
    for peer in directory["peers"]:
        lines.extend(["", "[[peers]]"])
        for key in ["name", "virtual_ip", "public_ip", "public_port", "owner", "updated_at", "expires_at"]:
            lines.append(f"{key} = {json.dumps(peer[key])}")
    return "\n".join(lines) + "\n"


def publish(event, now):
    """GitHub contents API's SHA precondition prevents lost concurrent updates."""
    import base64
    import os
    import subprocess
    import time
    from urllib.parse import quote
    repo = os.environ["GITHUB_REPOSITORY"]
    branch = os.environ["REGISTRY_BRANCH"]

    def read(path):
        response = subprocess.run(
            ["gh", "api", f"repos/{repo}/contents/{path}?ref={quote(branch, safe='')}"],
            check=True, capture_output=True, timeout=30,
        )
        entry = json.loads(response.stdout)
        raw = base64.b64decode(entry["content"], validate=False)
        if len(raw) > MAX_BYTES:
            raise ValueError("Registry file exceeds size limit")
        return tomllib.loads(raw.decode()), entry["sha"]

    for attempt in range(5):
        enrollment, _ = read("network/members.toml")
        directory, sha = read("network/peers.toml")
        result = update(event, enrollment, directory, now)
        if result == directory:
            return
        payload = json.dumps({
            "message": "Update public peer directory",
            "branch": branch,
            "sha": sha,
            "content": base64.b64encode(encode(result).encode()).decode(),
        })
        response = subprocess.run(
            ["gh", "api", "--method", "PUT", f"repos/{repo}/contents/network/peers.toml", "--input", "-"],
            input=payload, text=True, capture_output=True, timeout=30,
        )
        if response.returncode == 0:
            return
        if "409" not in response.stderr and "422" not in response.stderr:
            raise ValueError("GitHub rejected the update; check workflow permissions and branch protection")
        time.sleep(attempt + 1)
    raise ValueError("Concurrent updates prevented publication; submit a fresh request")


def main():
    import os
    import time
    event = json.loads(Path(os.environ["GITHUB_EVENT_PATH"]).read_text())
    if "--publish" in sys.argv:
        publish(event, int(time.time()))
        return
    enrollment = tomllib.loads(Path("network/members.toml").read_text())
    path = Path("network/peers.toml")
    raw = path.read_bytes()
    if len(raw) > MAX_BYTES:
        raise ValueError("Directory exceeds size limit")
    directory = tomllib.loads(raw.decode())
    result = update(event, enrollment, directory, int(time.time()))
    if result != directory:
        path.write_text(encode(result), encoding="utf-8")


if __name__ == "__main__":
    try:
        main()
    except (ValueError, KeyError, TypeError) as error:
        print(f"Registry request rejected: {error}", file=sys.stderr)
        sys.exit(1)
